version: '3.8'

services:
  bot:
    build:
      context: ./bot
      dockerfile: ../docker/Dockerfile.bot
    volumes:
      - ./bot:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    networks:
      - minecraft-bot-network

  web:
    build:
      context: ./web
      dockerfile: ../docker/Dockerfile.web
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - bot
    networks:
      - minecraft-bot-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - minecraft-bot-network

networks:
  minecraft-bot-network:
    driver: bridge
